import { StyleSheet } from '@react-pdf/renderer'

export const styles = StyleSheet.create({
  page: {
    backgroundColor: '#ffffff',
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 48,
    fontFamily: 'Helvetica',
    fontSize: 9,
    color: '#111827',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 32,
  },
  studioName: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 11,
    color: '#111827',
    textAlign: 'right',
  },
  heading: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 26,
    color: '#111827',
    marginBottom: 20,
  },
  clientBlock: {
    marginBottom: 24,
  },
  clientLabel: {
    fontSize: 8,
    color: '#6b7280',
    marginBottom: 2,
    textTransform: 'uppercase',
  },
  clientValue: {
    fontSize: 10,
    color: '#111827',
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderBottomColor: '#111827',
    paddingBottom: 6,
    marginBottom: 2,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingVertical: 7,
    alignItems: 'center',
  },
  colDesc: { flex: 5, fontSize: 9, color: '#111827' },
  colQty: { flex: 1, fontSize: 9, color: '#111827', textAlign: 'right' },
  colPrice: { flex: 2, fontSize: 9, color: '#111827', textAlign: 'right' },
  colTotal: { flex: 2, fontSize: 9, color: '#111827', textAlign: 'right' },
  headerCell: { fontFamily: 'Helvetica-Bold', fontSize: 8, color: '#6b7280', textTransform: 'uppercase' },
  totalsSection: {
    marginTop: 16,
    alignItems: 'flex-end',
  },
  totalsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 180,
    paddingVertical: 3,
  },
  totalsLabel: { fontSize: 9, color: '#6b7280' },
  totalsValue: { fontSize: 9, color: '#111827', textAlign: 'right' },
  grandTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 180,
    paddingVertical: 6,
    borderTopWidth: 2,
    borderTopColor: '#111827',
    marginTop: 4,
  },
  grandTotalLabel: { fontFamily: 'Helvetica-Bold', fontSize: 10, color: '#111827' },
  grandTotalValue: { fontFamily: 'Helvetica-Bold', fontSize: 10, color: '#111827', textAlign: 'right' },
  paymentSection: {
    marginTop: 28,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 16,
  },
  sectionTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 9,
    color: '#111827',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  paymentLabel: { fontSize: 9, color: '#374151' },
  paymentValue: { fontSize: 9, color: '#111827' },
  termsSection: {
    marginTop: 24,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 12,
  },
  termsText: {
    fontSize: 7.5,
    color: '#6b7280',
    lineHeight: 1.5,
  },
})
