ALTER TABLE public.line_items ADD COLUMN IF NOT EXISTS descuento NUMERIC(5,2) NOT NULL DEFAULT 0;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS descuento_general NUMERIC(5,2) NOT NULL DEFAULT 0;
